name: 'Recreate container action'
description: 'access portainer and recreate docker container'
inputs:
  portainer-host:
    description: 'Host deployed portainer'
    required: true
  username:
    description: 'username of portainer'
    required: true
  password:
    description: 'password of portainer'
    required: true
  stack-id:
    description: 'id of current stack'
    required: true
  container-name:
    description: 'name of container need to recreate'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'