name: 'Recreate container action'
description: 'access portainer and recreate docker container'
inputs:
  portainer-connect-uri:
    description: 'username@password@Host to connect portainer'
    required: true
  stack-id:
    description: 'id of current stack'
    required: true
  image-uri:
    description: 'name of container need to recreate'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'